### ISSUE TITLE
Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference

### ISSUE THREAD

**Issue by GobindaSaha** [dimaportenko/react-native-receive-share-file-tutorial#1]
Sir I'm getting **[Error: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference]** multiple times whenever I put the app in background and then open it. Any suggestions? I'm using functional compoent. Also implemented the way you explained in this video.

**Code ::**

const getFilesPage = () => {
    const [share, setShare] = useState(undefined);

    useEffect(() => {
        ReceiveSharingIntent.getReceivedFiles((files) => {
            console.log('Received Files', files);
            setShare(files);
        },
            error => {
                console.log(error);
            }, // share url protocol (must be unique to your app, suggest using your apple bundle id)
        );
    }, [share]); <======== **I set side effect here** =====>
    return share;
}

**Comment by dimaportenko** [comment]
Share in the dependencies list is definitely wrong. What do you expect to happen when you add it?

**Comment by GobindaSaha** [comment]
Sir, I want to build an app where I can receive and show the received data. Whenever I receive such data I want to update the view with the latest one. But if I don't put 'share' as dependancy in the useEffect seems not working, only it works first time then the new received data not updated in the view. @dimaportenko

**Comment by dimaportenko** [comment]
Try to put useShare hook into the root component of the app. And check if share value updates each time.
