### ISSUE TITLE
React Native build failed In iOS for react-native-share-file-tutorial repo

### ISSUE THREAD

**Issue by irfanchaudhry12** [dimaportenko/react-native-receive-share-file-tutorial#2]
CompileC /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SharedPromise.o /Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/RCT-Folly/folly/futures/SharedPromise.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
    cd /Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /Users/macbookpro/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.5-21F77-c098706a9f71eba4e76ae92ab367209a.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/macbookpro/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Index.noindex/DataStore @/Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_HAVE_PTHREAD\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-documentation -faligned-new -include /Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Target\ Support\ Files/RCT-Folly/RCT-Folly-prefix.pch -MMD -MT dependencies -MF /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SharedPromise.d --serialize-diagnostics /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SharedPromise.dia -c /Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/RCT-Folly/folly/futures/SharedPromise.cpp -o /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SharedPromise.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/SharedPromise.o

/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'React-Codegen' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'libevent' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'boost' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-Boost-iOSX' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-Fmt' from project 'Pods')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNRecieveShareTutorial' from project 'RNRecieveShareTutorial')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RNRecieveShareTutorial' from project 'RNRecieveShareTutorial')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'CocoaAsyncSocket' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'FlipperKit' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'SocketRocket' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'fmt' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'YogaKit' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'hermes-engine' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-Glog' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'OpenSSL-Universal' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'react-native-receive-sharing-intent' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-Folly' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper-RSocket' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'Flipper' from project 'Pods')
/Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'RCT-Folly' from project 'Pods')

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:D16C40D9-A0B9-41C5-B3C9-F1A8CAB4F9B3, OS:17.5, name:iPhone 13 }
{ platform:iOS Simulator, id:D16C40D9-A0B9-41C5-B3C9-F1A8CAB4F9B3, OS:17.5, name:iPhone 13 }
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/macbookpro/Library/Developer/Xcode/DerivedData/RNRecieveShareTutorial-gydlzsmmzvwtkqgnbfcsqfutpsfw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/arm64/json.o /Users/macbookpro/Projects/react-native-receive-share-file-tutorial/ios/Pods/RCT-Folly/folly/json.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
macbookpro@APPLEs-MacBook-Pro react-native-receive-share-file-tutorial %         
<img width="1512" alt="Screenshot 2024-11-24 at 7 40 40 AM" src="https://github.com/user-attachments/assets/f5bd685c-cf4d-4918-86cd-25b190345adc">
<img width="1512" alt="Screenshot 2024-11-24 at 7 42 23 AM" src="https://github.com/user-attachments/assets/cd87e955-01ca-4b54-84f1-097fe446f39f">

**Comment by irfanchaudhry12** [comment]
Sir I have committed on your Facebook video and you replied paste your issue with complete description on GitHub repo. Sir please help me in this issue

**Comment by irfanchaudhry12** [comment]
Showing Recent Errors Only
Cycle inside Sortara; building could produce unreliable results. This usually can be resolved by moving the shell script phase '[CP-User] [RNFB] Core Configuration' so that it runs before the build phase that depends on its outputs.
Cycle details:
→ Target 'Sortara' has process command with output '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist'
○ Target 'Sortara' has copy command from '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Share.appex' to '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/PlugIns/Share.appex'
○ That command depends on command in Target 'Sortara': script phase “[CP-User] [RNFB] Core Configuration”


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/_CodeSignature ->

command: P0:target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:CodeSign /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app ->

CYCLE POINT ->

node: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist ->

node: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist ->

command: P0:target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:ProcessInfoPlistFile /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist /Users/macbookpro/Projects/sortara-mobile/ios/Sortara/Info.plist ->

node: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/PlugIns/Share.appex ->

command: P0:target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:Copy /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/PlugIns/Share.appex /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Share.appex ->

node: <target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6--fused-phase5--cp-user---rnfb--core-configuration> ->

command: P0:::Gate target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6--fused-phase5--cp-user---rnfb--core-configuration ->

node: <execute-shell-script-500c994aa236de94e35a9b1c73a749faf3871d4c105c8363cfe1193577988b84-target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6-> ->

command: P2:target-Sortara-500c994aa236de94e35a9b1c73a749fa7ceb6b36bcfc2fb90f69ac96de4975d6-:Debug:PhaseScriptExecution [CP-User] [RNFB] Core Configuration /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Intermediates.noindex/Sortara.build/Debug-iphonesimulator/Sortara.build/Script-B9782A7BAE51D5E2C7E5BAE5.sh ->

node: /Users/macbookpro/Library/Developer/Xcode/DerivedData/Sortara-ecihvbfjchpdzefitkrxwsedtbrz/Build/Products/Debug-iphonesimulator/Sortara.app/Info.plist/




this is the error I m facing in my project after configuration in iOS

**Comment by dimaportenko** [comment]
hi @irfanchaudhry12, thank you for the bug report. I resolved build errors for iOS. Now you can download this project again try to build for iOS.
